SimpleCrm/SimpleCrm.Web/ViewComponents/GreetingViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace SimpleCrm.Web.ViewComponents
{
    public class GreetingViewComponent : ViewComponent
    {
        private readonly IGreeter greeter;

        public GreetingViewComponent(IGreeter greeter)
        {
            this.greeter = greeter;
        }

        //public IViewComponentResult Invoke()
        //{
        //    var model = greeter.GetGreeting();
        //    return View("Default", model);
        //}

        public Task<IViewComponentResult> InvokeAsync()
        {
            var model = greeter.GetGreeting();
            return Task.FromResult<IViewComponentResult>(View("Default", model));
        }
    }
}

SimpleCrm/SimpleCrm.Web/ViewComponents/LoginLogoutViewComponent.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace SimpleCrm.Web.ViewComponents
{
    public class LoginLogoutViewComponent : ViewComponent
    {
        private readonly UserManager<CrmUser> userManager;

        public LoginLogoutViewComponent(UserManager<CrmUser> userManager)
        {
            this.userManager = userManager;
        }

        public Task<IViewComponentResult> InvokeAsync()
        {
            var user = userManager.Users.FirstOrDefault(x => x.UserName == User.Identity.Name);
            return Task.FromResult<IViewComponentResult>(View(user));
        }
    }
}

SimpleCrm/SimpleCrm.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <environment include="Development">
        <link rel="stylesheet" href="/css/vendor.min.css">
        <script src="/js/vendor.min.js"></script>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.teal-pink.min.css"
            asp-fallback-href="/css/vendor.min.css"
            asp-fallback-test-class="mdl-layout__header-row"
            asp-fallback-test-property="display"
            asp-fallback-test-value="flex">
        <script defer src="https://code.getmdl.io/1.3.0/material.min.js"
            asp-fallback-src="/js/vendor.min.js"
            asp-fallback-test="window.MaterialButton"></script>
    </environment>
    <link rel="stylesheet" href="/css/site.css">
</head>
<body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
        <header class="mdl-layout__header">
            <div class="mdl-layout__header-row">
                <!-- Title -->
                <span class="mdl-layout-title">Simple CRM</span>
                <!-- Add spacer, to align navigation to the right -->
                <div class="mdl-layout-spacer"></div>
                <!-- Navigation. We hide it in small screens. -->
                <nav class="mdl-navigation mdl-layout--large-screen-only">
                    <a class="mdl-navigation__link" href="/">Customers</a>
                    @await Component.InvokeAsync("LoginLogout")
                </nav>
            </div>
        </header>
        <!-- TODO: main content area -->
        <div class="mdl-layout__drawer">
            <span class="mdl-layout-title">Simple CRM</span>
            <nav class="mdl-navigation">
                <a class="mdl-navigation__link" href="/">Customers</a>
                @await Component.InvokeAsync("LoginLogout")
                <a class="mdl-navigation__link" asp-action="Register" asp-controller="Account">Register</a>
            </nav>
        </div>
        <div>
            @RenderBody()
        </div>
        <!-- TODO: footer area -->
        <footer class="mdl-mini-footer">
            <div class="mdl-mini-footer__left-section">
                @await Component.InvokeAsync("Greeting")
            </div>
            <div class="mdl-mini-footer__right-section">
                <ul class="mdl-mini-footer__link-list">
                    <li><a href="#">&copy; @DateTime.Now.Year</a></li>
                    <li><a href="#">Ryan Lavery</a></li>
                    @RenderSection("footer", required: false)
                </ul>
            </div>
        </footer>
    </div>
    <script src="/js/vendor-post.min.js"></script>
</body>
</html>